# This is a generated file. Not intended for manual editing.
version: "3"
services:
  backend:
    build:
      context: "/mnt/c/Users/aleja/Desktop/Code/webFullStackTest/backend"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/backend.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "backend:dev"
    ports: []
    volumes:
    - "/mnt/c/Users/aleja/.nuget/packages:/root/.nuget/packages"
    - "/mnt/c/Users/aleja/Desktop/Code/webFullStackTest/backend:/app:rw"
    - "/mnt/c/Users/aleja/Desktop/Code/webFullStackTest:/src:rw"
    working_dir: "/app"
